#!/usr/bin/env bash

die()
{
    echo 1>&2 "ERROR: $*"
    exit 1
}

mydir="$(dirname "$0")"

build_target_only()
{
    "$mydir"/build_kiwix_target --assume-packages-installed \
                                --skip-source-prepare       \
                                --build-nodeps              \
                                "$1"
}

if [ $# -eq 0 ]
then
    targets=(kiwix-lib kiwix-tools)
else
    targets=("$@")
fi

for t in "${targets[@]}"
do
    build_target_only "$t" || die "target '$t' failed"
done
