#!/usr/bin/env bash

die()
{
  echo >&2 "ERROR: $*"
  exit 1
}

myname=$(basename "$0")

if [ $# -lt 2 ]
then
    cat<<END
Usage:

    $myname <mode> <project> <testargs> ...

Examples:

    $myname static libzim
    $myname dyn kiwix-lib
    $myname dyn zim-tools
END
    exit 1
fi

mode=$1
project=$2
shift 2
testargs=("$@")
mydir=$(dirname "$0")
mydir=$(cd "$mydir"; pwd)
srcdir=$mydir/SOURCE/$project
builddir=$mydir/BUILD_native_$mode/$project

test -d "$srcdir" || die "No such directory: $srcdir"
cd "$builddir" || die "No such directory: $builddir"
source_files=$(find "$srcdir" -name '*.h' -o -name '*.cpp' -o -name meson.build)

export SKIP_BIG_MEMORY_TEST=1
ulimit -v 5000000

keep_doing "meson test -v --timeout-multiplier 0.1 ${testargs[*]}" $source_files
