#!/usr/bin/env bash

cd "$(dirname "$0")"

ZIMNAME=wikipedia_en_climate_change_nopic_2020-01

serve()
{
    BUILD_native_static/INSTALL/bin/kiwix-serve -p 8888 -d -a "$1"\
            zimfiles/orig/"$ZIMNAME".zim
}

sleep 5 &
pid=$!
serve $pid
sleep 1
echo '------- Home page'
curl -I http://localhost:8888/
echo '------- An article'
curl -I http://localhost:8888/"$ZIMNAME"/A/Polar_bear
