#!/usr/bin/env bash

myname=$(basename "$0")

die()
{
    echo >&2 "ERROR: $*"
    exit 1
}

if [ $# -ne 1 ]
then
    echo>&2 "Usage: $myname <subdir>"
    exit 1
fi

rename()
{
    local src=$1 dest=$2
    test ! -e "$dest" && mv "$src" "$dest"
}

subdir=$1
parentdir=$(dirname "$subdir")
cd "$parentdir" || die "Cannot cd to directory: $parentdir"
subdir=$(basename "$subdir")
bakdirname="${subdir}.bak"
test -d "$subdir" || die "No such subdirectory: $subdir"
rename "$subdir" "$bakdirname" || die "Cannot rename '$subdir' to '$bakdirname'"
tmpdir=$(mktemp -d -p /dev/shm)
export TMPDIR=$tmpdir
builddir="$tmpdir/$(basename "$subdir")"
cp -r "$bakdirname" "$builddir"
ln -s "$builddir" .
cleanup()
{
    rm -rf "$tmpdir"
    rm "$subdir"
    mv "$bakdirname" "$subdir" || "Failed to restore the renamed directory '$bakdirname'"
}
trap cleanup EXIT
(cd "$subdir"; export CCACHE_DISABLE=1; exec bash)
