#!/usr/bin/env bash

#export LD_LIBRARY_PATH=$(pwd)/BUILD_native_dyn/INSTALL/lib/x86_64-linux-gnu
gdb -x debug_kiwix-serve.gdb -args ./kiwix-serve -t 1 --port 8080 wikipedia_en_geography_maxi_2025-09.zim |& tee gdb.log
