#!/usr/bin/env bash

mydir=$(readlink -f "$(dirname "$0")")

cd "$mydir"

. venv/bin/activate

rm -rf download

tmpdir=$(mktemp -d -p /dev/shm)
export TMPDIR=$tmpdir
mkdir "$tmpdir"/download
ln -s "$tmpdir"/download .

cleanup()
{
    kill %1 %2
    wait
    rm -rf "$tmpdir" "$mydir"/download
}

trap cleanup EXIT


./kiwix-serve --library --port 8080 library.xml &
#python -m http.server --directory zims 26913 &
cd zims
python -m RangeHTTPServer 26913 &

sleep 1

export KIWIX_CATALOG_HOST=localhost
export KIWIX_CATALOG_PORT=8080
if ../run_kiwix-desktop
then
    echo "$(tput setaf 2)========== OK ============$(tput setaf 7)"
else
    echo "$(tput setaf 1)########### ERROR #############$(tput setaf 7)"
fi
